### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by glados01** [StarDustSheep/StarDust#1]
我很喜欢这个主题,但有几个建议:
1. 笔记中PDF标注的样式和普通引用块的样式完全一样,能否区分一下?
2. 荧光效果看起来稍微有些模糊,能否优化?
3. PDF的颜色配置能不能同步修改一下?

**Comment by StarDustSheep** [comment]
己记录，我会找时间看看能不能改进的

**Comment by StarDustSheep** [comment]
已全部改进
