### ISSUE TITLE
/emoji 表情的输入展示排版有问题

### ISSUE THREAD

**Issue by xsinbh** [StarDustSheep/StarDust#6]
<img width="422" alt="屏幕截图 2023-04-20 220013" src="https://user-images.githubusercontent.com/112634985/233390088-4af8b759-cc66-4703-aed2-e6c1bc01f23e.png">
输入表情符号的排版乱了，表情的preview只有两列，希望实现像原版那样就好

**Comment by StarDustSheep** [comment]
下个版本修复
